#!/usr/bin/env bash
# load-ssm-env.sh
#
# Reads all parameters from AWS SSM Parameter Store at /ai-tutor/prod/ and
# writes them to .env on EC2. Called during each deployment so that secret
# updates in SSM take effect without manual SSH.
#
# Usage (on EC2 or from SSM Run Command):
#   ./scripts/load-ssm-env.sh
#
# Environment overrides:
#   SSM_PATH    SSM path prefix   (default: /ai-tutor/prod/)
#   ENV_FILE    Output .env path  (default: /home/ubuntu/AI-Tutor-Agent/.env)
#   REGION      AWS region        (default: ap-southeast-2)
#
# To update a secret without redeploying code:
#   aws ssm put-parameter --region ap-southeast-2 \
#     --name /ai-tutor/prod/DEEPGRAM_SECRET_KEY \
#     --value "new-value" --type SecureString --overwrite
#   # Then either re-run deploy or SSH and run this script + restart Docker

set -euo pipefail

SSM_PATH="${SSM_PATH:-/ai-tutor/prod/}"
ENV_FILE="${ENV_FILE:-/home/ubuntu/AI-Tutor-Agent/.env}"
REGION="${REGION:-ap-southeast-2}"

echo "Reading SSM parameters from ${SSM_PATH} (region: ${REGION})"

# Uses boto3 (pip3 install boto3) — no AWS CLI required.
# Falls back gracefully with a clear error if boto3 is missing.
SSM_PATH="${SSM_PATH}" ENV_FILE="${ENV_FILE}" REGION="${REGION}" python3 - <<'PYEOF'
import sys, os

try:
    import boto3
except ImportError:
    print("ERROR: boto3 not installed. Run: pip3 install boto3", file=sys.stderr)
    sys.exit(1)

ssm_path = os.environ["SSM_PATH"]
env_file  = os.environ["ENV_FILE"]
region    = os.environ["REGION"]

client = boto3.client("ssm", region_name=region)

params = []
paginator = client.get_paginator("get_parameters_by_path")
for page in paginator.paginate(
    Path=ssm_path,
    Recursive=True,
    WithDecryption=True,
):
    params.extend(page["Parameters"])

if not params:
    print(f"ERROR: No SSM parameters found at {ssm_path}", file=sys.stderr)
    sys.exit(1)

lines = [
    "# Generated by scripts/load-ssm-env.sh from AWS SSM Parameter Store",
    "# Do not edit manually — update via: aws ssm put-parameter --overwrite",
    "",
]

required = {
    "AUTH_JWT_SECRET", "DEEPGRAM_SECRET_KEY", "NEO4J_PASSWORD",
    "AWS_DEFAULT_REGION", "DYNAMODB_TABLE_NAME",
    "DYNAMODB_AUTH_USERS_TABLE", "DYNAMODB_ASSESSMENT_TABLE",
    "SQS_JOBS_QUEUE_URL", "S3_ASSESSMENT_BUCKET", "ALLOW_ORIGINS",
}
found = set()

for p in sorted(params, key=lambda x: x["Name"]):
    key   = p["Name"]
    value = p["Value"]

    if key.startswith(ssm_path):
        key = key[len(ssm_path):]

    found.add(key)

    if any(c in value for c in (" ", "\t", "#")):
        value = '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines.append(f"{key}={value}")

missing = required - found
if missing:
    print("ERROR: Required SSM parameters are missing:", file=sys.stderr)
    for k in sorted(missing):
        print(f"  {ssm_path}{k}", file=sys.stderr)
    sys.exit(1)

import tempfile, os
tmp = env_file + ".tmp"
with open(tmp, "w") as f:
    f.write("\n".join(lines) + "\n")
os.replace(tmp, env_file)

print(f"Wrote {len(params)} env vars to {env_file}")
PYEOF
